name: rive
description: Rive 2 Flutter Runtime
version: 0.6.0
repository: https://github.com/rive-app/rive-flutter
homepage: https://rive.app

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphs: ^0.2.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
